import {
  SiNextdotjs,
  SiReact,
  SiTypescript,
  SiMongodb,
  SiRedis,
  SiDocker,
  SiNginx,
  SiPrisma,
  SiOpenai,
  SiCloudflare,
  SiGithubactions,
  SiNestjs,
  SiPostgresql,
  SiSequelize,
  SiNodedotjs,
  SiSass,
  SiBootstrap,
  SiTailwindcss,
  SiCss3,
  SiHtml5,
  SiJavascript,
  SiExpo,
  SiJest,
  SiSwagger,
  SiExpress,
  SiChartdotjs,
  SiReactquery,
  SiAxios,
} from 'react-icons/si';
import { TbBrandReactNative, TbBrandFramerMotion } from 'react-icons/tb';
import { FaLeaf } from 'react-icons/fa';

const techIconsMap = {
  'Next.js': { icon: SiNextdotjs, color: '#ffffff' },
  React: { icon: SiReact, color: '#61DAFB' },
  TypeScript: { icon: SiTypescript, color: '#3178C6' },
  MongoDB: { icon: SiMongodb, color: '#47A248' },
  Redis: { icon: SiRedis, color: '#DC382D' },
  Docker: { icon: SiDocker, color: '#2496ED' },
  Nginx: { icon: SiNginx, color: '#009639' },
  Prisma: { icon: SiPrisma, color: '#ffffff' },
  OpenAI: { icon: SiOpenai, color: '#412991' },
  Cloudflare: { icon: SiCloudflare, color: '#F38020' },
  'GitHub Actions': { icon: SiGithubactions, color: '#2088FF' },
  NestJS: { icon: SiNestjs, color: '#E0234E' },
  'React Native': { icon: TbBrandReactNative, color: '#61DAFB' },
  PostgreSQL: { icon: SiPostgresql, color: '#4169E1' },
  Sequelize: { icon: SiSequelize, color: '#52B0E7' },
  'Node.js': { icon: SiNodedotjs, color: '#339933' },
  SASS: { icon: SiSass, color: '#CC6699' },
  Bootstrap: { icon: SiBootstrap, color: '#7952B3' },
  'Tailwind CSS': { icon: SiTailwindcss, color: '#06B6D4' },
  'Framer Motion': { icon: TbBrandFramerMotion, color: '#0055FF' },
  CSS3: { icon: SiCss3, color: '#1572B6' },
  HTML5: { icon: SiHtml5, color: '#E34F26' },
  JavaScript: { icon: SiJavascript, color: '#F7DF1E' },
  Expo: { icon: SiExpo, color: '#ffffff' },
  Jest: { icon: SiJest, color: '#C21325' },
  WebSocket: { icon: SiNodedotjs, color: '#339933' },
  Swagger: { icon: SiSwagger, color: '#85EA2D' },
  Express: { icon: SiExpress, color: '#ffffff' },
  'Chart.js': { icon: SiChartdotjs, color: '#FF6384' },
  Recharts: { icon: SiReact, color: '#61DAFB' },
  'React Query': { icon: SiReactquery, color: '#FF4154' },
  Zustand: { icon: SiReact, color: '#61DAFB' },
  Axios: { icon: SiAxios, color: '#5A29E4' },
  Leaflet: { icon: FaLeaf, color: '#199900' },
  JWT: { icon: SiNodedotjs, color: '#339933' },
  Bcrypt: { icon: SiNodedotjs, color: '#339933' },
  NextAuth: { icon: SiNextdotjs, color: '#ffffff' },
  'Google Maps API': { icon: SiReact, color: '#4285F4' },
  'WhatsApp API': { icon: SiReact, color: '#25D366' },
  'Text-to-Speech API': { icon: SiOpenai, color: '#412991' },
  'Rich Text Editor': { icon: SiReact, color: '#61DAFB' },
  'React Hook Form': { icon: SiReact, color: '#EC5990' },
  AsyncStorage: { icon: TbBrandReactNative, color: '#61DAFB' },
  'Push Notifications': { icon: TbBrandReactNative, color: '#61DAFB' },
  'Expo Location': { icon: SiExpo, color: '#000020', bg: '#ffffff' },
  'React Navigation': { icon: TbBrandReactNative, color: '#61DAFB' },
  'Linear Gradient': { icon: TbBrandReactNative, color: '#61DAFB' },
  'Vector Icons': { icon: TbBrandReactNative, color: '#61DAFB' },
  'React Native Blur': { icon: TbBrandReactNative, color: '#61DAFB' },
  Lottie: { icon: TbBrandReactNative, color: '#00DDB3' },
  'Class Validator': { icon: SiNestjs, color: '#E0234E' },
  'Class Transformer': { icon: SiNestjs, color: '#E0234E' },
  AOS: { icon: SiCss3, color: '#1572B6' },
};

export default techIconsMap;
